name             'oracle'
maintainer       'Christos Kapasakalidis'
maintainer_email 'xkapasakal@gmail.com'
license          'All rights reserved'
description      'Installs/Configures oracle'
long_description 'Installs/Configures oracle'
version          '0.1.0'
depends          'yum'
depends          'yum-epel'
